# -*- coding: utf-8 -*-
"""covid-19_ase_in_malaysia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kUQ2DyRSRCYo0Fg2lRGKAfBUSN4MtdPQ
"""

import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset
data = pd.read_csv("/content/cases_state.csv")

# Display the first 5 rows
print(data.head())

# Optionally: Display some basic statistics or visualize the data
data.describe()

# If it's suitable for a plot:
data.plot()
plt.show()